## Numpy

### 1. array creation

In [2]:
import numpy as np

In [3]:
a = np.arange(15)
print a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(15,)

In [6]:
a.size

15

In [7]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
a = np.arange(15).reshape(3,5)

In [10]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.shape

(3, 5)

In [12]:
a.size

15

In [13]:
a.ndim

2

In [14]:
b = np.array([3,5,7,6,'a'])

In [15]:
b

array(['3', '5', '7', '6', 'a'],
      dtype='|S21')

In [16]:
b[0]

'3'

In [17]:
type(b[0])

numpy.string_

In [20]:
c = np.array([3,5,7,6])

In [21]:
c

array([3, 5, 7, 6])

In [22]:
c.dtype

dtype('int64')

In [23]:
d = np.array((3,5,7,6))

In [24]:
d

array([3, 5, 7, 6])

 **sintaxis es `np.array(iterable)`**

In [25]:
np.array(1,3,5)

ValueError: only 2 non-keyword arguments accepted

In [26]:
np.array([1,3,5])

array([1, 3, 5])

In [27]:
np.array([[1,3,5], [6,8,10]])

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [28]:
np.zeros([3,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [29]:
np.ones([3,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [35]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [36]:
np.linspace(1, 10, 2)

array([  1.,  10.])

### 2. operations

In [37]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [38]:
print b

[0 1 2 3]


In [39]:
a - b

array([20, 29, 38, 47])

In [40]:
b**2

array([0, 1, 4, 9])

In [42]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [43]:
a<40

array([ True,  True, False, False], dtype=bool)

In [44]:
a == 40

array([False, False,  True, False], dtype=bool)

In [47]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
print A
print
print B

[[1 1]
 [0 1]]

[[2 0]
 [3 4]]


In [48]:
A*B  # elemento por elemento

array([[2, 0],
       [0, 4]])

In [49]:
A.dot(B)  # producto punto

array([[5, 4],
       [3, 4]])

In [50]:
a

array([20, 30, 40, 50])

In [51]:
a.sum()

140

In [52]:
a.min()

20

In [53]:
a.max()

50

In [54]:
a.mean()

35.0

In [55]:
a.std()

11.180339887498949

In [57]:
a.cumsum()

array([ 20,  50,  90, 140])

In [58]:
a = np.arange(15).reshape(3,5)

In [59]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
a.sum()

105

In [61]:
a.sum(axis=0)

array([15, 18, 21, 24, 27])

In [62]:
a.sum(axis=1)

array([10, 35, 60])

In [63]:
a.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27]])

In [64]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

### 3. Indexing, Slicing and Iterating

### 4. Stacking

### 5. Grids

In [66]:
X, Y = np.meshgrid([1,2,3],[4,5,6])

In [67]:
X

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [68]:
Y

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])